
# [[language]]
# name = "yaml"
# file-types = ["yml"]
# language-server = "yaml-language-server"
# config = {
#   yaml = {}

#     customTags = [
#         "!And scalar",
#         "!If scalar",
#         "!Not",
#         "!Equals scalar",
#         "!Or scalar",
#         "!FindInMap scalar",
#         "!Base64",
#         "!Cidr",
#         "!Ref",
#         "!Sub",
#         "!GetAtt sequence",
#         "!GetAZs",
#         "!ImportValue sequence",
#         "!Select sequence",
#         "!Split sequence",
#         "!Join sequence"
#     ],
#     schemas: {
#        "https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json": "/**/cf-templates/*.yml"
#    }
#   }
# }

