# Check if grm is available and switch to it
if grm --version > /dev/null 2>&1; then
  alias rm="grm"
fi

# Check if gtar is available and switch to it
if gtar --version > /dev/null 2>&1; then
  alias tar="gtar"
fi

# enable color support of ls
dircolors_command="dircolors"
if gdircolors --version > /dev/null 2>&1; then
  dircolors_command="gdircolors"
fi

# Check if gls is available and switch to it
if gls --version > /dev/null 2>&1; then
  ls_alias_set gls
fi
