# User iterm2 shell integration if it exists
if [ -e "${HOME}/.iterm2_shell_integration.bash" ] ; then
  source "${HOME}/.iterm2_shell_integration.bash"
fi

# Automatically added when installing n
#export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
