#!/usr/bin/env zsh

# TODO: unused file
# TODO: appending to zshrc conflicts with WORK config.

# Android on macOS
MACOS_ANDROID="${HOME}/Library/Android"
if [ -d "${MACOS_ANDROID}" ]; then
  export ANDROID_HOME="${MACOS_ANDROID}/sdk"
  export ANDROID_SDK_ROOT="${MACOS_ANDROID}/sdk"
  export PATH="${PATH}:${ANDROID_HOME}/tools/bin"
  export PATH="${PATH}:${ANDROID_HOME}/platform-tools"
  export PATH="${PATH}:${ANDROID_HOME}/emulator"
fi
unset MACOS_ANDROID
