#
# ~/.bash_aliases
#
# This file contains user-specific aliases.
#

# ls aliases
# On some platforms, this can be used with alternative tools
ls_alias_set() {
  local LS_EXECUTABLE=$1
  local LS_FLAG_COLOR=""
  local LS_FLAG_GROUP_DIRECTORIES_FIRST=""
  local LS_FLAG_HUMAN_SIZE=""
  local LS_FLAG_INDICATOR=""

  if [ -n $LS_EXECUTABLE ]; then
    return 1
  fi

  # reset possible previous aliases
  unalias ls
  unalias sl
  unalias LS
  unalias l
  unalias ll
  unalias la
  unalias lla

  # Add color
  if ${LS_EXECUTABLE} --color=auto >/dev/null 2>&1; then
    LS_FLAG_COLOR="--color=auto"
  elif ${LS_EXECUTABLE} -G >/dev/null 2>&1; then
    LS_FLAG_COLOR="-G"
  fi

  # Human-readable size
  if ${LS_EXECUTABLE} -h >/dev/null 2>&1; then
    LS_FLAG_HUMAN_SIZE="-h"
  fi

  # Add specific indicator after directory/socket/link/...
  if ${LS_EXECUTABLE} -F >/dev/null 2>&1; then
    LS_FLAG_INDICATOR="-F"
  fi

  if ${LS_EXECUTABLE} --group-directories-first >/dev/null 2>&1; then
    LS_FLAG_GROUP_DIRECTORIES_FIRST="--group-directories-first"
  fi

  local ls_command="${LS_EXECUTABLE} ${LS_FLAG_COLOR} ${LS_FLAG_INDICATOR} ${LS_FLAG_HUMAN_SIZE} ${LS_FLAG_GROUP_DIRECTORIES_FIRST}"
  # More ls aliases
  alias ls=${ls_command}
  alias sl=${ls_command}
  alias LS=${ls_command}
  alias l=${ls_command}" -l"
  alias ll=${ls_command}" -l"
  alias la=${ls_command}" -A"
  alias la=${ls_command}" -A"
  alias lla=${ls_command}" -lA"
}
ls_alias_set ls


# Other color aliases
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


# Default to human readable figures
alias df='df -h'
alias du='du -h'


# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'


# List only users processes
alias myps="ps axo user,tty,ppid,pid,command | grep -vE \"grep|ps axo\" | grep -E \"(USER\s*PPID)|$USER\""
alias mypsa="ps aux | grep -vE \"grep|ps aux\" | grep -E \"(USER\s*PID)|$USER\""


# Exit less if the output is small enough for only one screen
alias less='less -F'


# Force showing all output using tail
alias ftail='tail -f -n+1'


# SSH with logging
alias logssh='ssh > >(tee ssh-$(date +"%Y-%m-%d-%H-%M").out) 2> >(tee ssh-$(date +"%Y-%m-%d-%H-%M").err >&2)'
