#
# ~/.bash_profile
#
# This file is executed by bash for login shells.
#

# Source user's comnands file for helper functions.
if [ -f "${HOME}/.bin/commands.sh" ]; then
  . "${HOME}/.bin/commands.sh"
fi

# Bash won't source .profile if this ~/.bash_profile exists.
source_if_exists "${HOME}/.profile"

# Source the personal bashrc if it exists.
source_if_exists "${HOME}/.bashrc"

# Use better competion if it exists.
# TODO: Consider moving to ~/.profile.
source_if_exists "${HOME}/.bin/git-completion.bash"
if command_exists "brew"; then
  BREW_PATH="$(brew --prefix)"
  source_if_exists "${BREW_PATH}/etc/bash_completion.d/git-completion.bash"
  source_if_exists "${BREW_PATH}/etc/bash_completion.d/git-prompt.sh"
  unset BREW_PATH
fi

# TODO: move to profile.
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

source_if_exists "${HOME}/.iterm2_shell_integration.bash"
