#
# ~/.bash_profile: executed by bash(1) for login shells.
#
# User dependent .bash_profile file
#

# Source the users bashrc if it exists
if [ -f "${HOME}/.bashrc" ] ; then
  source "${HOME}/.bashrc"
fi

# Set PATH so it includes user's private bin if it exists
if [ -d "${HOME}/.bin" ] ; then
  PATH="${HOME}/.bin:${PATH}"
fi

# Set MANPATH so it includes users' private man if it exists
if [ -d "${HOME}/man" ]; then
  MANPATH="${HOME}/man:${MANPATH}"
fi

# Set INFOPATH so it includes users' private info if it exists
if [ -d "${HOME}/info" ]; then
  INFOPATH="${HOME}/info:${INFOPATH}"
fi

# Use better bash competion if it exists
if [ -f "${HOME}/.bin/git-completion.bash" ] ; then
  source "${HOME}/.bin/git-completion.bash"
fi

if [ -f "${HOME}/.bin/git-prompt.sh" ] ; then
  source "${HOME}/.bin/git-prompt.sh"
fi

# User iterm2 shell integration if it exists
if [ -e "${HOME}/.iterm2_shell_integration.bash" ] ; then
  source "${HOME}/.iterm2_shell_integration.bash"
fi
