#
# ~/.bash_profile
#
# File is sourced by bash for login shells.
#

# Source common profile file if it exists
if [ -f "${HOME}/.profile" ]; then
  source "${HOME}/.profile"
fi

# Source the users bashrc if it exists
if [ -f "${HOME}/.bashrc" ] ; then
  source "${HOME}/.bashrc"
fi

# Set PATH so it includes user's private bin if it exists
if [ -d "${HOME}/.bin" ] ; then
  PATH="${HOME}/.bin:${PATH}"
fi

# Set MANPATH so it includes users' private man if it exists
if [ -d "${HOME}/man" ]; then
  MANPATH="${HOME}/man:${MANPATH}"
fi

# Set INFOPATH so it includes users' private info if it exists
if [ -d "${HOME}/info" ]; then
  INFOPATH="${HOME}/info:${INFOPATH}"
fi

# Use better bash competion if it exists
if [ -f "${HOME}/.bin/git-completion.bash" ] ; then
  source "${HOME}/.bin/git-completion.bash"
fi

if [ -f "${HOME}/.bin/git-prompt.sh" ] ; then
  source "${HOME}/.bin/git-prompt.sh"
fi

