#!/usr/bin/env zsh
#
# ~/.zshrc
#

# Source the users commands library if it exists.
if [ -f "${HOME}/.bin/commands.sh" ]; then
  . "${HOME}/.bin/commands.sh"
fi

# Load personal shell rc file.
source_if_exists "${HOME}/.shellrc"

#
## oh-my-zsh
#

# Path to the oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Plugins for oh-my-zsh.
# Default plugins can be found in ~/.oh-my-zsh/plugins/
# Custom plugins may be found n ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  dircycle dotenv shrink-path
)

# Load certain plugins only if needed.
if command_exists "brew"; then
  plugins+=(brew)
fi

if command_exists "docker"; then
  plugins+=(docker)
fi

if command_exists "git"; then
  plugins+=(git gitfast git-extras)
fi

if command_exists "gradle"; then
  plugins+=(gradle)
fi

if command_exists "pacman"; then
  plugins+=(archlinux)
fi

if [ -d "${ZSH}/custom/plugins/alias-tips" ]; then
  plugins+=(alias-tips)
fi

# Set name of the theme to load.
# Optionally, set to "random" and oh-my-zsh will use a random theme each time it is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Let the oh-my-zsh magic begin.
. "${ZSH}/oh-my-zsh.sh"


#
## Powerline customization
#
() {
  # Overwrite default prompts. Default values:
  # POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
  # POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)
  typeset -ga POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
  typeset -ga POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs virtualenv)

  # Prompt separators.
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=" →"
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=" "
  typeset -g POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=
  typeset -g POWERLEVEL9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS=" "

  ## context
  # colors
  typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND=none
  typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=clear
  # Remove hostname from prompt.
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE="%n"

  ## dir
  # colors
  typeset -g POWERLEVEL9K_DIR_{ETC,HOME,HOME_SUBFOLDER,DEFAULT,NOT_WRITABLE}_BACKGROUND=none
  typeset -g POWERLEVEL9K_DIR_{ETC,HOME,HOME_SUBFOLDER,DEFAULT,NOT_WRITABLE}_FOREGROUND=blue
  typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR_FOREGROUND=cyan
  # Shorten directory path:
  # How many directory to show in full.
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  # Truncate from end of directory names.
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right
  # Remove delimiter in truncated strings.
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=

  ## vcs
  # colors
  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED,LOADING}_BACKGROUND=none
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=green
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=magenta
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=yellow
  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_{REMOTE_URL,COMMIT,BRANCH,TAG,REMOTE_BRANCH,STAGED,UNSTAGED,UNTRACKED,OUTGOING_CHANGES,INCOMING_CHANGES,STASH,ACTION}FORMAT_FOREGROUND
  typeset -g POWERLEVEL9K_VCS_UNTRACKEDFORMAT_FOREGROUND=magenta
  typeset -g POWERLEVEL9K_VCS_UNSTAGEDFORMAT_FOREGROUND=red
  typeset -g POWERLEVEL9K_VCS_STAGEDFORMAT_FOREGROUND=green
  typeset -g POWERLEVEL9K_VCS_CLEAN_BRANCHFORMAT_FOREGROUND=green
  typeset -g POWERLEVEL9K_VCS_{UNTRACKED,MODIFIED}_BRANCHFORMAT_FOREGROUND=yellow
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGESFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STASHFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_CLEAN_FOREGROUND
  typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_ACTIONFORMAT_FOREGROUND=red
  # Remove any icons.
  typeset -g POWERLEVEL9K_VCS_{GIT,GIT_GITHUB,GIT_BITBUCKET,GIT_GITLAB,BRANCH}_ICON=
  # Show file count for git repos.
  typeset -g POWERLEVEL9K_VCS_STAGED_MAX_NUM=-1
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_MAX_NUM=-1
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_MAX_NUM=99

  ## status
  # colors
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=none
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=red
  # Hide OK status.
  typeset -g POWERLEVEL9K_STATUS_OK=false
  # Hide weird CR arrow-like.
  typeset -g POWERLEVEL9K_CARRIAGE_RETURN_ICON=

  ## background_jobs
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=none
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_COLOR=green
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON="%%"
} "%@"

# Load aliases.
source_if_exists "${HOME}/.aliases"

# Load zsh-syntax-highlighting.
if command_exists "brew"; then
  BREW_PREFIX="$(brew --prefix)"
  source_if_exists "${BREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
  FPATH="${BREW_PREFIX}/share/zsh/site-functions:$FPATH"
  source_if_exists "${BREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi
