[tools]
# Languages
go = "latest"
java = "temurin"
kotlin = "latest"
lua = "latest"
node = "lts"
python = ["3.11", "3"]
# Git
delta = "latest"
github-cli = "latest"
gitui = "latest"
lefthook = "latest"
# Build
gradle = "latest"
maven = "latest"
# Scala
coursier = "latest"
sbt = "latest"
scala-cli = "latest"
# Cloud and infra
awscli = "latest"
eksctl = "latest"
kubectl = "latest"
kubectx = "latest"
kubelogin = "latest"
minikube = "latest"
terraform = "latest"
# Misc
glow = "latest"
tree-sitter = "latest"
shellcheck = "latest"
pipx = "latest"

# Stable enough for me to use it as a daily driver.
neovim = "nightly"
