[settings]
experimental = true

[tools]
# Languages
go = "latest"
java = "corretto"
node = "lts"
python = "3"
# Git
delta = "latest"
github-cli = "latest"
gitui = "latest"
lefthook = "latest"
# Build
gradle = "latest"
maven = "latest"
# Scala
coursier = "latest"
sbt = "latest"
scala-cli = "latest"
# Cloud and infra
awscli = "latest"
eksctl = "0.149.0"  # Check manually for next ones or improve the plugin. Using "latest" does not work with downloading.
kubectl = "latest"
kubectx = "latest"
kubelogin = "latest"
minikube = "latest"
terraform = "latest"
# Misc
glow = "latest"

# Stable enough for me to use it as a daily driver.
neovim = "nightly"
tree-sitter = "latest"
